### get all products

GET http://localhost:8080/products HTTP/1.1

### get a single product: <id>

GET http://localhost:8080/products/0 HTTP/1.1

### get all product categories

GET http://localhost:8080/products/categories HTTP/1.1

### get all products by category: <category>

GET http://localhost:8080/products/categories/cheatsheets HTTP/1.1

### limit product results

GET http://localhost:8080/products?limit=2 HTTP/1.1

### sort resutls: 'asc' or 'desc'

GET http://localhost:8080/products?sort=desc HTTP/1.1


### create new product

POST http://localhost:8080/products HTTP/1.1
content-type: application/json

{ 
    "name": "The C++ Programming Language",
    "description": "C++11, C++14, C++17, C++20",
    "category": "books",
    "image": "",
    "price": 29.99
}

### Update a single product

PUT http://localhost:8080/products/0 HTTP/1.1
content-type: application/json

{ 
    "name": "The C++ Programming Language",
    "description": "Modern C++",
    "category": "cheatsheet",
    "image": "",
    "price": 49.99
}

### Update attributes of a specific product

PATCH http://localhost:8080/products/0 HTTP/1.1
content-type: application/json

{  
    "price": 21.38
}

### Delete a product

DELETE http://localhost:8080/products/0 HTTP/1.1

#####################################################################

### Get all carts

GET http://localhost:8080/carts HTTP/1.1

### Get all carts with a limit size

GET http://localhost:8080/carts?limit=2 HTTP/1.1

### Get all carts sorted in ascending or descending order

GET http://localhost:8080/carts?sort=asc HTTP/1.1


### Get single cart

GET http://localhost:8080/carts/2 HTTP/1.1

### Get all carts of a specific user

GET http://localhost:8080/carts/user/0 HTTP/1.1

### Get all carts in a date range

GET http://localhost:8080/carts/startdate=2021-10-24&enddate=2022-01-10 HTTP/1.1

###

GET http://localhost:8080/carts/startdate=2021-02-24 HTTP/1.1

###

GET http://localhost:8080/carts/enddate=2022-02-24 HTTP/1.1

### Add new cart

POST http://localhost:8080/carts HTTP/1.1
content-type: application/json

{ 
    "userId": 1,
    "products": [
        {
            "product_id": 2,
            "quantity": 4
        }
    ]
}

### Delete a single cart

DELETE http://localhost:8080/carts/2 HTTP/1.1

### Update single cart

PUT http://localhost:8080/carts/0 HTTP/1.1
content-type: application/json

{ 
    "userId": 3,
    "products": [
        {
            "product_id": 2,
            "quantity": 4
        },
        {
            "product_id": 5,
            "quantity": 4
        }
    ]
}

### Update cart attributes

PATCH http://localhost:8080/carts/0 HTTP/1.1

{ 
    "products": [
        {
            "product_id": 1,
            "quantity": 3
        },
        {
            "product_id": 2,
            "quantity": 5
        },
        {
            "product_id": 3,
            "quantity": 6
        }
    ]
}

### Get all users

GET http://localhost:8080/users HTTP/1.1


### Get single user

GET http://localhost:8080/users/1 HTTP/1.1

### Add new user

POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{ 
    "username": "imariom",
    "password": "Mutemba32",
    "name": "Mario Moiane",
    "phone": "846659087",
    "city": "Matola, Maputo-Mozambique",
    "street": "Av. 25 de Setembro", 
    "number": 13178,
    "zip_code": "4548"
}

### Update single user

PUT http://localhost:8080/users/1 HTTP/1.1
content-type: application/json

{ 
    "username": "bear",
    "password": "2292n^722-/2$#@!",
    "name": "Julia Punk",
    "phone": "8239042",
    "city": "Latorre, Comores",
    "street": "LaTorre De Sa", 
    "number": 13178,
    "zip_code": "4548"
}


### Update user attributes

PATCH http://localhost:8080/users/1 HTTP/1.1
content-type: application/json

{ 
    "username": "marilia",
    "password": "marilia32",
    "name": "julia",
    "number": 12345
}

### Delete single user

DELETE http://localhost:8080/users/1 HTTP/1.1