### List all products

GET http://localhost:8080/products HTTP/1.1

### Get a single product

GET http://localhost:8080/products/0 HTTP/1.1

### Add new product
POST http://localhost:8080/products HTTP/1.1
content-type: application/json

{ 
    "name": "The Go Programming Language",
    "description": "Modern, fast, reliable and productive",
    "category": "books",
    "image": "",
    "price": 49.99
}

### Update a single product

PUT http://localhost:8080/products/0 HTTP/1.1
content-type: application/json

{ 
    "name": "The C++ Programming Language",
    "description": "Modern C++",
    "category": "books",
    "image": "",
    "price": 49.99
}

### Update attributes of a specific product

PATCH http://localhost:8080/products/0 HTTP/1.1
content-type: application/json

{  
    "price": 21.38
}

### Get all categories

GET http://localhost:8080/products/categories HTTP/1.1

### Get all products in a specific category

GET http://localhost:8080/products/categories/hats HTTP/1.1

### Delete a product

DELETE http://localhost:8080/products/0 HTTP/1.1


### Get all carts

GET http://localhost:8080/cart HTTP/1.1


### Get all users

GET http://localhost:8080/users HTTP/1.1


### Get single user

GET http://localhost:8080/users/02 HTTP/1.1

### Add new user

POST http://localhost:8080/users HTTP/1.1
content-type: application/json

{ 
    "username": "imariom",
    "password": "Mutemba32",
    "name": "Mario Moiane",
    "phone": "846659087",
    "city": "Matola, Maputo-Mozambique",
    "street": "Av. 25 de Setembro", 
    "number": 13178,
    "zip_code": "4548"
}